baseURL = 'https://orgesified.com/'
languageCode = 'en-us'
title = 'Orges'
defaultContentLanguage = "en"

theme = "DoIt"

[params]
# DoIt theme version
version = "0.4.0"

  defaultTheme = "auto"
  enablePWA = false
  cacheRemoteImages = true
  # [Experimental] generate image srcset attribute with hugo image processing feature.
  optimizeImages = true

  [params.author]
    name = "orges"
    email = "orges@orgesified.com"
    link = "https://github.com/orges"
    avatar = "/avatar.png"

  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "orges"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = ""
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"

  [params.image]
    # cache remote images for better optimisations
    cacheRemote = true
    # Image resizing and optimisation
    optimise = true

  # Footer config
  [params.footer]
    enable = false

  # Home page config
  [params.home]
   # DoIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = "orges@orgesified.com"
      # URL of avatar shown in home page
      # Place your avatar file under static or assets directory
      # The filepath is relative to the static or assets directory
      #avatarURL = "/avatar.png"
      # URL the avatar links to
      avatarLinkURL = "https://github.com/orges"
      # whether to show social links
      social = true
      # subtitle shown in home page
      subtitle = "CS Graduate, Android Hobbyist. Love Learning Cultures & Languages. And Cats."

  # Social config about the author
  [params.social]
    GitHub = "orges"
    Telegram = "orges"
    Twitch = "orgese"
    Bilibili = "orgesu"
    Email = "orges@orgesified.com"
    Twitter = "orgesui"

    # DoIt CHANGED | 0.2.10 Page SEO config
    [params.page.seo]
      # Publisher info
      [params.page.seo.publisher]
        name = "Orges"
        logoUrl = "/avatar.png"
[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

